### ISSUE TITLE
python train_reward_model.py module 'tensorflow' has no attribute 'data'

### ISSUE THREAD

**Issue by charley12009** [jianzhnie/open-chatgpt#40]
When I run "python train_reward_model.py", I get the following error. How can I solve it?
Python version 3.10.8

Traceback (most recent call last):
  File "C:\Users\charley\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1110, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\charley\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\charley\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\trainer.py", line 67, in <module>
    from .data.data_collator import DataCollator, DataCollatorWithPadding, default_data_collator
  File "C:\Users\charley\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\data\__init__.py", line 31, in <module>
    from .processors import (
  File "C:\Users\charley\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\data\processors\__init__.py", line 19, in <module>
    from .glue import glue_convert_examples_to_features, glue_output_modes, glue_processors, glue_tasks_num_labels
  File "C:\Users\charley\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\data\processors\glue.py", line 79, in <module>
    examples: tf.data.Dataset,
AttributeError: module 'tensorflow' has no attribute 'data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Windows\System32\open-chatgpt\examples\summarization\train_reward_model.py", line 4, in <module>
    from transformers import (AutoTokenizer, EarlyStoppingCallback, EvalPrediction,
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\charley\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1100, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\charley\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1112, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
module 'tensorflow' has no attribute 'data'

**Comment by charley12009** [comment]
when I use "pyhton train_reaward_model.py" have a Runtime Error in reward_model.py line 182:stack expects each tensor to be equal size, but got [41] at entry 0 and [139] at entry 1
Because deepspeed cannot be installed on windows，so I use this project in colab，and execution type is GPU.
Please tell me as soon as possible how to solve the problem of runtime error, thanks.

**Comment by jianzhnie** [comment]
I have updated the code, please try again
